[package]
name = "hack-hydra-dx-wasm"
version = "0.1.0"
authors = ["Martin Hloska <martin.hloska@topmonks.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = {version = "0.2.63"}
hack-hydra-dx-math = { version = "0.1.0", git = "https://github.com/galacticcouncil/hack.hydraDX-math" , branch="main"}

[profile.release]
opt-level = "s"
