[package]
authors = ['GalacticCouncil']
edition = '2018'
license = 'Apache 2.0'
name = "hydra-dx-wasm"
repository = 'https://github.com/galacticcouncil/hydradx-wasm'
version = "3.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = {version = "0.2.68"}
wee_alloc = { version = "0.4.5", optional = true }

#hydra-dx-math = {version = "4.0.0"}
hydra-dx-math = { path ="../HydraDX-math" }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[features]
xyk = []
lbp = []

